name: Python Flask App CI

on: [workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests with pytest
      run: |
        pytest

    - name: Run Flask app (optional)
      if: github.event_name == 'push'
      run: |
        nohup python app.py &
        sleep 5
        curl http://localhost:5000 || echo "Flask app not reachable"